### ISSUE TITLE
Unintended duplication of task with threshold date

### ISSUE THREAD

**Issue by bnoellert** [mjdescy/TodoTxtMac#105]
I'm using 2.1.1 and have the "hide future tasks" behavior selected.  
Any tasks that I use with a threshold date get duplicated upon reloading (typing '.') todo.txt.  This seems to be independent of whether the date is in the future or whether it has passed.  
*Steps to reproduce:*
1. Create a task with a threshold date in the future
2. Save
3. Reload using '.'
4. The task will still be hidden, but if you open the file with an editor you will see that task was duplicated.

This also starts to become multiplicative if you don't notice it because the next time it will duplicate both the original and the duplicate task...and so forth...I ended up with about 20 copies of one task before I realized what was happening.

**Comment by mjdescy** [comment]
This has been a nagging problem. I think I finally fixed it tonight.

**Comment by mjdescy** [comment]
This change will be in version 2.2.0, which is due imminently.
