### ISSUE TITLE
Can't add tasks or open lists with custom region settings

### ISSUE THREAD

**Issue by antonlarin** [mjdescy/TodoTxtMac#108]
I customized time representation through System Preferences on my system and that apparently doesn't work well with TodoTxtMac. The app doesn't add tasks (pressing Enter simply removes focus from TextArea) and it doesn't open existing lists. To be more specific, I'm using the preset for Russian region but with 12-hour time format (default is 24-hour).

I used the debugger and found out that `NSDateFormatter` fails to parse the fake due date and returns `nil` [here](https://github.com/mjdescy/TodoTxtMac/blob/master/TodoTxtMac/TTMTask.m#L208) which then it's being used [here](https://github.com/mjdescy/TodoTxtMac/blob/master/TodoTxtMac/TTMTask.m#L437), causing the exception. Adding `[dateFormatter setLocale:[NSLocale systemLocale]];` after [that line](https://github.com/mjdescy/TodoTxtMac/blob/master/TodoTxtMac/TTMDateUtility.m#L62) seems to fix the issues that I'm experiencing, but I don't know whether that could be considered a solution.

**Comment by mjdescy** [comment]
@antonlarin Thank you for this bug report. I was wondering when locale-related bugs would surface.

I will look into your proposed solution and try to see if it has any unintended consequences. Thanks for being so thorough.

**Comment by mjdescy** [comment]
@antonlarin Try version 2.2.2. It should fix your bug.

**Comment by antonlarin** [comment]
That was really quick, thank you.
