### ISSUE TITLE
Building on Mavericks fails.

### ISSUE THREAD

**Issue by MartyLake** [mjdescy/TodoTxtMac#109]
Hi,

Tried to build on 10.9.5, got these errors during the "compile XIB files" phase. The mainmenu.xib compiled without warning, but the others raised 4 errors. Any chance of getting your app to compile for Mavericks ? :)

I'm a complete noob in objectiveC, but I can try to execute instructions for you if that can help  ! 

Best

--------------------------------------

`2016-05-30 09:49:05.071 ibtoold[5921:507] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException
/* com.apple.ibtool.errors */
/Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/TodoTxtMac/Base.lproj/TTMDocument.xib: error: The document "(null)" requires at least Xcode 7.0 and Mac OS 10.11.
    Recovery Suggestion: This version does not support stacking Non-gravity area distributions on NSStackView. Open this document with at least Xcode 7.0 and Mac OS 10.11.`

`2016-05-30 09:49:05.071 ibtoold[5920:507] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException
/* com.apple.ibtool.errors */
/Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/TodoTxtMac/TTMTasklistMetadata.xib: error: The document "(null)" requires at least Xcode 7.0 and Mac OS 10.11.
    Recovery Suggestion: This version does not support stacking Non-gravity area distributions on NSStackView. Open this document with at least Xcode 7.0 and Mac OS 10.11.`

`CompileXIB TodoTxtMac/TTMPreferences.xib
    cd /Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module TodoTxtMac --minimum-deployment-target 10.11 --output-partial-info-plist /Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/DerivedData/TodoTxtMac/Build/Intermediates/TodoTxtMac.build/Debug/TodoTxtMac.build/TTMPreferences-PartialInfo.plist --auto-activate-custom-fonts --output-format human-readable-text --compile /Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/DerivedData/TodoTxtMac/Build/Products/Debug/TodoTxtMac.app/Contents/Resources/TTMPreferences.nib /Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/TodoTxtMac/TTMPreferences.xib

2016-05-30 09:49:05.071 ibtoold[5922:507] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException
/* com.apple.ibtool.errors */
/Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/TodoTxtMac/TTMPreferences.xib: error: The document "(null)" requires at least Xcode 7.0 and Mac OS 10.11.
    Recovery Suggestion: This version does not support box content view or stacking Non-gravity area distributions on NSStackView. Open this document with at least Xcode 7.0 and Mac OS 10.11.`

`/* com.apple.ibtool.errors */
/Users/neogaldr/Downloads/mjdescy-TodoTxtMac-f80d48f/TodoTxtMac/TTMFilters.xib: error: The document "(null)" requires at least Xcode 7.0 and Mac OS 10.11.
    Recovery Suggestion: This version does not support stacking Non-gravity area distributions on NSStackView. Open this document with at least Xcode 7.0 and Mac OS 10.11.
2016-05-30 09:49:05.919 ibtoold[5920:507] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException`

**Comment by mjdescy** [comment]
Hi, Matthieu,

Since version 2.0.0, TodoTxtMac no longer supports Mavericks. The minimum OS X version supported is now 10.11. That is why you can’t compile.

I dropped support for older versions mostly due to the age of the OS, the Mac hardware cycle (basically everything released in the past 3 years or so supports the latest OS X version), and I was getting compiler warnings on my end (OS X 10.11) about deprecated features and so on.

You could try to hack on an older commit, or upgrade your OS if your machine supports it. (Honestly, El Capitan runs as fast or faster than Mavericks did on my 2013-era machine.) The only code that really requires OS X 10.11 is the view code (the .xib files).

**Comment by MartyLake** [comment]
Sadness :(

I really can't upgrade my mac there because I use it for audio production and know for sure things will break when upgrading.

Thanks for your answer anyway ;)
