### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by mhalano** [mjdescy/TodoTxtMac#111]
I think the idea behind TodoTxtMac is amazing: Easy with lots of shortcuts. I think should be available for Linux too. The easy way is port to Swift because Swift is available for Linux. I think is relatively hard but the effort will payback. :)

**Comment by mjdescy** [comment]
That's a nice idea, but I don't think I'm up for a Linux port. Someone else is free to try, though.

Swift *is* available for Linux, but none of Foundation or AppKit has been ported, so it really would not be possible to port TodoTxtMac.
