### ISSUE TITLE
Recurring task wrongly applied to completed tasks

### ISSUE THREAD

**Issue by dbadol** [mjdescy/TodoTxtMac#124]
Hello,

When a recurring task is completed, it's next instance is correctly created:
```
(A) 2017-04-29 Pay NET @Internet t:2017-06-01 due:2017-06-01 rec:+1m
x 2017-04-29 2017-04-04 Pay NET @Internet t:2017-05-01 due:2017-05-01 rec:+1m
```
However, if I edit the completed task (here, in order to add the priority that was lost during completion), yet another instance is created:
```
(A) 2017-04-29 Pay NET @Internet t:2017-06-01 due:2017-06-01 rec:+1m
(A) 2017-04-29 Pay NET @Internet t:2017-06-01 due:2017-06-01 rec:+1m
x 2017-04-29 (A) 2017-04-04 Pay NET @Internet t:2017-05-01 due:2017-05-01 rec:+1m
```
I guess it would make more sense if editing _completed_ tasks **would not** trigger the creation of another instance of the recurring task.

Cheers,
David

**Comment by mjdescy** [comment]
@dbadolato Your suggestion is reasonable. I will see what I can do.
