### ISSUE TITLE
ENH - Consider auto refresh option

### ISSUE THREAD

**Issue by georgecc** [mjdescy/TodoTxtMac#19]
I use several machines during the day, moving from one to the other. Now that I can get ToDoTxt on the Mac, it is an even more useful tool. I run one of the apps simultaneously  on all the machines I am using (Windows, MacBook, iMac, Android phone).
When I make changes on one machine I need to manually refresh on the others.
What about an option that would trigger automatic background updates every few minutes. Maybe the number of minutes should be user-tuneable.

**Comment by mjdescy** [comment]
Finally!
