### ISSUE TITLE
Enh - Visible sign/mark of which filter is being applied?

### ISSUE THREAD

**Issue by darrenkenny** [mjdescy/TodoTxtMac#31]
I love the ability to change filters by simply typing 0-9, but it would be nice to have 
some sort of visual feedback as to what filter is being currently applied. 

I might also be good in that case, to allow the user to also specify a 'name' for the filter
to be displayed?

For example, in the title, where the name of the file is you could have something like:

     todo.txt (Filtered: Filter 1)

or in a status bar at the bottom?

**Comment by mjdescy** [comment]
A user-customizable (and optional) status bar will allow you to see which filter preset and sort are applied, as well as display some task list metadata. This feature will be implemented in the version 1.4.0.
