### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by sdaitzman** [mjdescy/TodoTxtMac#47]
I love the app but the icon feels a tiny bit dated... how's this? I've attached a PNG of my take on it, and if you like it I can send it over in Sketch, Illustrator, or SVG format. Feel free to use it with or without credits to me, and thanks for the great project!

![todotxtmacicon](https://cloud.githubusercontent.com/assets/1499476/5554145/fbd04de4-8c11-11e4-9053-39f1a5932177.png)

I used the same colors as the original icon but tried to make it feel more like native OS X app icons, with a single smooth gradient and thinner checkmark. I kept the borders very similar to the current icon, but it also looks gorgeous without them:

![todotxtmaciconnoborders](https://cloud.githubusercontent.com/assets/1499476/5554161/a01735ac-8c12-11e4-8ac0-7227ed639d8e.png)

Let me know what you think!

**Comment by mjdescy** [comment]
@sdaitzman Thanks again for the icon. I really like it. I will push out a release sometime in January that will change the icon and add a couple new features. If you can send me a SVG version of the icon, I'd appreciate it!

**Comment by sdaitzman** [comment]
Here's that SVG: http://f.cl.ly/items/3E2c1s0U1l0P1B1J2U3s/todotxtmac.svg

Also, I made a slightly more refined version:

![todotxtmac](https://cloud.githubusercontent.com/assets/1499476/5605828/9dd54566-93df-11e4-87b1-0dcc43b922e0.png)

What do you think? Here's an SVG for that one:

http://f.cl.ly/items/001R0Z0Q0O0F1G3x2R1A/todotxtmac.svg

I used the same gradient and embossing as the app store icon, but green!

**Comment by mjdescy** [comment]
Sam, that latest icon looks really good. I can't help think that the checkmark's angle looked better in the first two icons you sent me, though. I think the new one would be just about perfect if the checkmark were rotated slightly clockwise, so it matched the angle you used in the second (no-border) icon.

**Comment by sdaitzman** [comment]
How about this? :)

![todotxtmac](https://cloud.githubusercontent.com/assets/1499476/5608623/1f53199c-9458-11e4-8f02-d3b98f7ce387.png)

**Comment by sdaitzman** [comment]
The gradient seems a little wonky in the SVG but here: http://f.cl.ly/items/001R0Z0Q0O0F1G3x2R1A/todotxtmac.svg

**Comment by mjdescy** [comment]
@sdaitzman That last icon looks fantastic to me! Thanks for all your work! I will put the new icon into the dev branch soon. I am working on some other changes, and would rather close those out before changing the icon again. I plan to push out a new production release sometime this month.

**Comment by mjdescy** [comment]
The new icon will be published with version 1.3.0.
