### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by dddw** [mjdescy/TodoTxtMac#48]
This application is beautiful, alas I can't use it because of the lack of a threshold function.
I just have too many tasks to not have this, currenlty I use qtodotxt on mac and linux. Simpletask on android/blackberry.
For those who are unfamiliar with the threshold function:
adding a task such as this on below won't show up in your tasklist until the first of 2019(unless unchecked 'future tasks 'in settings) 
(A) call my lawyer @phone about +businessidea t:2019-01-01 due:2019-07-01
I would love to see this feature in a future release, together with keyboard shortcuts this app already has. this tool would totally help me be alot more productive.

Good luck!

**Comment by mjdescy** [comment]
@dddw I would like to implement this feature. I never knew about the threshold feature before, but it seems like a good idea. Do you envision it working within the existing filtering system? That would be the easiest approach, I think.

**Comment by dddw** [comment]
Yeah a quickfilter that can toggle future tasks on and off would be great!

**Comment by mjdescy** [comment]
Threshold date functionality will be published in version 1.3.0.

**Comment by dddw** [comment]
epic! ;)

**Comment by mjdescy** [comment]
You're welcome. :-)
