### ISSUE TITLE
Adding text to a todo in a filtered selection ending in loops under certain conditions

### ISSUE THREAD

**Issue by Shinoto-github** [mjdescy/TodoTxtMac#55]
Recently I started using filters and observed this behaviour, which I will explain with an example: 

I filter for all todos without a project, then I mark one or more todos which I will assign a certain project using "T" and adding something like "+projectname". I can enter this in the sheet, but the sheet will not disappear with OK or Cancel. I have to quit to get back to my todos. Then, nothing is altered. 

I assume this is because Todo.txt cannot save the altered todos because they do not any more fit to the conditions of the filter. 

Thanks, and thank you for this wonderful app.

**Comment by mjdescy** [comment]
@Shinoto-github Thanks for the bug report. Could you please give me more information about (or a screenshot of) the filter you are using for "all todos without a project"? I can't reproduce this bug, and I think it's because I don't quite understand what filter choices you are using.

**Comment by Shinoto-github** [comment]
Thank you so much. 

Here is the filter. Btw, I am working on Mountain Lion. 
![bildschirmfoto 2015-02-09 um 11 26 47](https://cloud.githubusercontent.com/assets/7529461/6100204/01836234-b04e-11e4-8b60-f2ee3d67c36e.png)

**Comment by mjdescy** [comment]
@Shinoto-github Thanks for the filter screenshot. I am not able to reproduce the bug on Yosemite in TodoTxtMac version 1.4.0. I can only run Yosemite at the moment, so it is not really possible for me to test alternative solutions. The alert windows' completion handlers are based on a compatibility method that I introduced to support OS X 10.8. I don't know what about that code would not be working for you. Do the other alert sheets (for set due date, postpone, etc.) work for you?

**Comment by Shinoto-github** [comment]
Thanks for looking into this.

Now I tried several other cases, but I have no problems with any of the 
sheets. It only occurs in 2 cases, and these have something in common:

A filter is set, and as soon as I append text, this particular todo does 
no longer fit into the selection for the filter. So it seems to me that 
todo.txt does not know how to procede, where to put the todo -- into the 
selection or somewhere else.

These 2 cases are: When I filter for "no context" or "no project" and 
then either add a context or a project to this todo.

Everything else works fine.

Besides: Thanks for this nice piece of software!

Am 09.02.15 um 23:37 schrieb Michael Descy:

**Comment by mjdescy** [comment]
Sorry about that problem. I just can't reproduce the behavior on Yosemite. 

When modifying a selected task would remove from the list due to the applied, the expected behavior is that the task is modified and is then hidden (filtered out). This will work even if all the task lists displayed before the change would be filtered out after the change. The modifications to the tasks occur after the modal sheet is dismissed, so that bit of code isn't causing the behavior you are seeing, unless the append command is somehow being reapplied after you dismissed the modal sheet.

I don't think I can fix this bug, though maybe someone with Xcode on Mountain Lion could look into it for us.

**Comment by Shinoto-github** [comment]
Hi,

thanks for taking your time anyway.

Problems of this kind are certainly not the developer's fault. I am 
quite upset with Apple's policy to force people into using a new OS 
almost every year -- with software getting incompatible with every 
update. I try to keep my Mac stable on Mountain Lion and prepare to 
leave the system as soon as my Macs will not work any more. A real pity 
when I think of the potential and beauty of OS X.

Best,
Maria





Am 10.02.15 um 22:52 schrieb Michael Descy:
