### ISSUE TITLE
Small list of suggestions

### ISSUE THREAD

**Issue by Brixy** [mjdescy/TodoTxtMac#56]
Thank you for your software. It is probably the best todo.txt editor for OS X you can find.

Here is a short list of suggestions, though:

- Remember window size and position
- Recognize URLs and make them clickable
- When sorting by priority, project, context …: sort the “rest” alphabetically
- Filter: maybe add `does not contain` for `task`
- Soft wrap long entries (e. g. max 2 or 3 visible lines)

Thank you very much!

**Comment by lalthomas** [comment]
:+1:

**Comment by mjdescy** [comment]
Thanks, @Brixy. I will keep these suggestions in mind.

**Comment by Brixy** [comment]
Thanks a lot, @mjdescy.

Here another two minor suggestions.

- It would be great, if it was possible to leave the “composing line” with a keyboard shortcut.
- In my workflow the shortcut ⌘← (remove priority) is somehow “tricky”, as most text editors use this command to move the curser to the beginning of the line (just like the home button).

**Comment by Brixy** [comment]
And another suggestion (maybe a real bug) for this brilliant piece of software:

TodoTxtMac remembers the previously selected filter on startup.

After a search, it forgets about the filter view, although the filter is checked off in the menu.

**Comment by mjdescy** [comment]
Thanks, @Brixy. That sounds like unintentional behavior. I will make an issue and the last bug report to my to-do list. Please file one issue per bug if you file any more in the future.

**Comment by mjdescy** [comment]
I am closing this issue. I will keep the other suggestions in mind. The most important ones are parts of other issues by now.
