### ISSUE TITLE
Setting threshold date fails when item is “filtered away”

### ISSUE THREAD

**Issue by Brixy** [mjdescy/TodoTxtMac#60]
Hi,

when a filter hiding all future threshold items is active, TodoTxtMac crashes when you add a threshold date to an item (⌥ S).

The item gets hidden immediately, but the calendar remains open and cannot be closed.

Thanks again, @mjdescy

**Comment by mjdescy** [comment]
Thanks for the bug report, @Brixy. 

I will be working on some filter-related bug fixes and improvements now. 

Some questions:
- Are you using threshold state or threshold date in your filter?
- Are you on Yosemite?

**Comment by Brixy** [comment]
Thanks a lot for your effort, @mjdescy.

Yes, I’m on Yosemite currently using to simple filters:

- threshold **state** is not in the future
- threshold **state** is in the future.

BTW: “is not” sometimes jumps to “is”, yet the filter still works properly.

**Comment by mjdescy** [comment]
Hi, @Brixy. I'd like to fix this for you, but I cannot reproduce the bug. I have some filter enhancements coming in the next version now, thanks to you, and maybe they will fix your problem, too.

**Comment by Brixy** [comment]
Cheers! Looking forward to your update.

**Comment by Brixy** [comment]
Superb. Bug disappeared in 1.5.0. Thank you very much.

**Comment by mjdescy** [comment]
Glad to hear it.
