### ISSUE TITLE
Custom font not used for priorities

### ISSUE THREAD

**Issue by robertvanbregt** [mjdescy/TodoTxtMac#68]
When using a custom font (e.g. Monaco), a priority like `(A)` is still shown in Arial font.

**Comment by mjdescy** [comment]
I see that. I think it is a side effect related to bolding the priority text. I will look into it.

**Comment by mjdescy** [comment]
I am working on a fix for this. Note that some fonts do not have bold variants, and after I issue a fix, priority will not be bolded for those fonts.

**Comment by mjdescy** [comment]
Closed in Version 1.5.1.
