### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#73]
Add context menu when the user right clicks / secundary clicks a tasks or selection of tasks. This should show all actions that can ben executed on that selection (mostly the items from the Task menu).

**Comment by lalthomas** [comment]
+1

**Comment by mjdescy** [comment]
I will think about this. It doesn't really go with my design approach to the app (providing tons of keyboard shortcuts as the primary way to do things). If I add all the commands to a context menu, that menu will be huge and obscure the task list.

**Comment by mjdescy** [comment]
@lalthomas You were right. Sorry I didn't see this your way last year. This feature will be released soon.
