### ISSUE TITLE
ENH - ability to resize the search bar

### ISSUE THREAD

**Issue by lalthomas** [mjdescy/TodoTxtMac#75]
As my project names and context name are pretty long, I couldn't read it after selecting it from suggestion list. It would be great if the size of the search bar persists for next restart.

**Comment by mjdescy** [comment]
I don't think this is possible--at least not in a way that makes for a good UI experience. Search bars in OS X toolbars aren't resizable at runtime via click-and-resize. It may be possible to adjust the size when the search box gets focus, and snap back to the original size when the search box loses focus. I'm not sure I would want to implement that behavior though. It seems like it would be odd. I'm going to label this "wontfix" for now, though I may return to it someday.
