### ISSUE TITLE
Filter never due items

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#76]
When you create a filter 'duestate is not due' the list contains both items with due dates not due and also items without a due date. Suggestion is to have the not due items show only if a due date is available and create a new duestate 'never due'.

Perhaps this also applies to treshold date and any other date (completed, created)?

**Comment by mjdescy** [comment]
In the next couple releases, I will make SwiftoDo and TodoTxtMac have the same definitions of "due state". I will most like add a "no due date" due state and a "no threshold date" threshold state. I have been trying to avoid that for psychological reasons, but I think I will give in and make separate states for when there is no due date or no threshold date.
