### ISSUE TITLE
Anyway to use it on OS X Lion (10.7)?

### ISSUE THREAD

**Issue by gastus1** [mjdescy/TodoTxtMac#82]
I would be very happy ))

**Comment by mjdescy** [comment]
Hi, @gastus1. I'm sorry to say that I cannot support OS X Lion. At this point, I can really only support the latest OS X version and try not to break anything that was built to work on Mountain Lion (10.8). I originally developed the app on Mavericks and have found that updates to OS X and Cocoa each year require minor changes to my code to keep TodoTxtMac working properly. I don't have the hardware to run older versions of OS X, and some of the Cocoa APIs I use are supported by 10.8 and up.
