### ISSUE TITLE
Hanging since 1.6.0

### ISSUE THREAD

**Issue by rcraggs** [mjdescy/TodoTxtMac#83]
Since the update to 1.6.0 it occasionally hangs at 100% CPU until I force close it (perhaps twice a day). This is with undos set to infinite. 

I'm not sure of the exact steps that reproduce it, but repeating the following steps eventually cause it. 

- Double click a task to edit it
- make a change
- press escape to undo the change
- click elsewhere on the UI

**Comment by mjdescy** [comment]
Thanks for the bug report. I was able to reproduce the problem a few times. I can't figure out how to reproduce it consistently, though. Perhaps it has something to do with a conflict between the undo/redo functionality that I created and the undo/redo that's built into the default user controls. It seems a lot harder to trigger this behavior if you don't have the option to use Escape to cancel all edits to a task enabled.

**Comment by okitac** [comment]
I'm also having something that looks like this issue -- repeated hangs, until a force quit, which may or may not be accompanied by high CPU usage -- and it's happening quite frequently (4 times in the last 90 minutes). 

I do have the option to use 'esc' to cancel all edits enabled, but the trigger for the hang seems to be trying to perform more actions/type too quickly when it's already trying to process one action.

Looking at the hang reports suggests this may be correct.  Please let me know if you need more information.

**Comment by mjdescy** [comment]
That Esc option triggers a loop of undo operations on the cell. I think that, since using the UndoManager for the task list, too, that there is something screwing up that loop, making it infinite.

**Comment by mjdescy** [comment]
You could revert to the prior version for a while, too. Undo/redo is the main benefit of 1.6.0.

**Comment by mjdescy** [comment]
@okitac I re-read your comment today and realized that you're talking about something that may have a separate root cause from the one @rcraggs originally reported. Version 1.6.0 is doing something it probably shouldn't--auto-saving on the main UI thread--which didn't pose any problems for me during my testing. I will see if I can get it to auto-save like it used to, without screwing up undo/redo.

**Comment by mjdescy** [comment]
Is anyone having hanging issues on version 1.6.1?

**Comment by okitac** [comment]
No hanging issues yet -- the update is failing to run correctly... something about problems extracting.

**Comment by mjdescy** [comment]
That sounds bad. Is that error message from the auto update within the app, or when you download from GitHub?

**Comment by okitac** [comment]
It's from the auto-update in the app -- I've tried it on two different laptops, with the same result.  It's fine when I download from GitHub -- and I'll see if I can get it to hang a bit later ;D

**Comment by mjdescy** [comment]
I was able to reproduce the auto-update failure. Honestly, I got lazy and didn't test the auto-update feature for 1.6.1. I think the zip file for 1.6.1 got corrupted somehow. GitHub is not allowing me to replace the zip files with a new one, though, which is problematic. I will try again tomorrow.

**Comment by mjdescy** [comment]
I fixed auto-update (Issue #84).
