### ISSUE TITLE
Filtering doesn't work with threshold date and threshold state

### ISSUE THREAD

**Issue by deletemonkey** [mjdescy/TodoTxtMac#87]
When filtering for threshold state "is in the past" or threshold date "is less than" a certain date, the filter returns all items matching the filter, PLUS all items with no threshold date at all. This makes it impossible to view a list of tasks which need to start today or should have started already. 

The same problem does not occur when filtering by due dates or due state, when tasks with no due date are successfully excluded. Likewise, when filtering for future threshold dates, tasks with no threshold date are also excluded.

This makes it difficult to work with TodoTxtMac if you use threshold dates because tasks you are meant to be starting or have started are buried away among less important or urgent things.

Maybe I'm doing something wrong? Any help appreciated.

**Comment by rtvbnl** [comment]
Possibly related to #76 ?

**Comment by mjdescy** [comment]
I am addressing this in version 2.1.0. 

1. I am adding a threshold state of "no threshold date", which will separate out the tasks with no threshold date. I am also changing the names of the threshold states to bring them in line with [SwiftoDo](http://swiftodoapp.com) v1.3.2. 

2. I am also adding a "hide future tasks" option to TodoTxtMac.
