### ISSUE TITLE
ENH: Duplicate selected tasks

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#90]
Duplicate selected tasks. Allow one or more selected tasks as input (just like append/prepend).
Suggested keyboard shortcut: D
Selection stays as is after action (no deselect or new selection) so you can perform a new action like completing the tasks.

Choice to be made: 

- insert new tasks just below last selected task (in the middle of the task list) 
- append tasks at the end of the task list

**Comment by mjdescy** [comment]
This does sound useful, but Command+C then Command+V will do this already, and is pretty quick to type. The new task is added to the end of the file, but will be sorted wherever it is supposed to go in the table view.

**Comment by rtvb** [comment]
Since issuing the request, I had found out the copy/paste possibility.
You can close this issue as far as I'm concerned.
