### ISSUE TITLE
ENH: horizontal scrolling for long items

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#91]
If items are longer than the window width, the app should support horizontal scrolling. The windows should scroll as far as the widest item or the widest visible item.

Currently the only way to view the item in the app is to edit it or to extend the window width.

**Comment by mjdescy** [comment]
Good point.

**Comment by mjdescy** [comment]
I worked on this a little. It was surprisingly difficult to implement without breaking something else. I think the ultimate solution isn't a scroll bar so much as a word wrap plus a dynamic row height. That, too, is more difficult than I thought it would be to implement, but we will get there someday.

**Comment by mjdescy** [comment]
Version 2.3.1 will close this issue.
