### ISSUE TITLE
Bug: pressing 'enter' or 'U' doesn't update task

### ISSUE THREAD

**Issue by scraggo** [mjdescy/TodoTxtMac#92]
Bug: pressing 'enter' or 'U' doesn't update task - it merely scrolls to and highlights a random task (the same one no matter what I do)
I'm running Version 1.6.1 (1.6.1) on Mac OS 10.8.5

**Comment by mjdescy** [comment]
@scraggo I am not sure what is going on with your install, but Mac OS 10.8 is no longer supported. I have no way of testing it.

**Comment by mjdescy** [comment]
I just observed this bug on version 2.1.0 running on Mac OS X 10.11.4. It arose after I updated to the OS X 10.11.4 release. The Enter key is acting as the "U" key and moving the selection to the first task beginning with "U". You can only edit that one task with Enter or the "U" key.

Workaround until I can fix this: Double-click the task and type in the edit.

**Comment by mjdescy** [comment]
Oddly, this bug just went away for me after I re-opened the issue. I will keep an eye on it. If any users can help me track it down, let me know.

**Comment by mjdescy** [comment]
I think I fixed this issue. The key command wasn't being sent to the correct control, and, for some reason, that was usually not a problem. I will continue to look for misbehavior in this. I will put out a new release later this week.
