### ISSUE TITLE
Unable to update from 1.6.1 to 2.0.0

### ISSUE THREAD

**Issue by eli-oat** [mjdescy/TodoTxtMac#95]
The app's auto update keeps getting hung up and displaying the following: 

![screen shot 2016-03-11 at 5 37 21 pm](https://cloud.githubusercontent.com/assets/3342274/13717527/23d2e0e0-e7b0-11e5-811a-4a75400e0bac.png)

I'm happy to delete the application and install fresh, but am not finding 2.0.0 on the releases page. 

(Running OS X 10.11.3, on a 13-inch, easy 2015 MacBook Air)

**Comment by mjdescy** [comment]
It will be released tonight sometime. I didn't mean to trigger the update mechanism ahead of time. Sorry about that.

**Comment by mjdescy** [comment]
Updates to 2.0.0 should be working now. I tested an upgrade from 1.6.1 on my system.

**Comment by eli-oat** [comment]
Worked like a charm! Super excited for the new version!
