### ISSUE TITLE
Option to automatically close the application when the last window is closed

### ISSUE THREAD

**Issue by nwinkler** [mjdescy/TodoTxtMac#99]
Since TodoTxtMac starts up pretty quickly, I would like to only open it when I need it - I don't want the application to linger around in my Dock.

When I have my `todo.txt` file open in the application and I simply close the window, the application will remain open without any visible window, and I have to quit it using the menu or the Dock icon.

It would be great to have an option that automatically quits the application when the last window is closed. This would save a couple of clicks each time I use it.

Thanks for the great app otherwise - I really like it!

**Comment by mjdescy** [comment]
I will think about this. I have other features I'm working on that I need to finish first.

In the meantime, type Command+Q to quickly exit the app. You don't need to close the task list window beforehand.

**Comment by nwinkler** [comment]
Thanks - yes I know about Command+Q, and I've been trying to keep using it consistently. I try to use the keyboard as much as possible, but I sometimes catch myself closing the window with the mouse.

**Comment by nwinkler** [comment]
That was quick! Thanks - looking forward to this enhancement :+1:
